### ISSUE TITLE
Quick question on how to incorporate GARCH into a state space model

### ISSUE THREAD

**Issue by aiyingyun** [ChadFulton/tsa-notebooks#14]

**Comment by ChadFulton** [comment]
Unfortunately statsmodels doesn't have anything built-in that would estimate a GARCH.  Estimation of a similar model by Bayesian methods is described in the stochastic volatility notebook, http://www.chadfulton.com/topics/stochastic_volatility_mcmc.html, but it is not a GARCH model, so that example would require some substantial adaptation.
