### ISSUE TITLE
Value Error: Array must not contain infs or NaNs when fitting model

### ISSUE THREAD

**Issue by IlanReinstein** [ChadFulton/tsa-notebooks#8]
I am trying to reproduce your code and I keep getting the same error when running the EstimateRBC on simulated data. Specifically, when trying to fit the model, in the following lines:

`
sim_mod=EstimateRBC1(output=sim_observed[:,0],labor=sim_observed[:,1],consumption=sim_observed[:,2],measurement_errors=True)
`

`
sim_res = sim_mod.fit(maxiter=1000, information_matrix_type='oim')
`

The problem only arises when I try running more than 50 iterations, below that, everything runs but I keep getting the same warning:
`
Warnings:
[1] Covariance matrix calculated using the outer product of gradients (complex-step)
`
I wonder if it is a problem with the fit() method? This has been a recurring problem with many Kalman Filter implementations in Python.

Thank you for your help.

**Comment by ChadFulton** [comment]
Thanks for letting me know!

It looks like near the end, the optimizer is trying out setting the discount rate parameter to zero, so that the (a bit sloppy) transformation ends up setting it to -0.0004.

As for the "Warning", that is not a problem and actually shouldn't be a warning. It's really just meant to inform the user how the covariance matrix is computed.

The other "Warning" that shows up, that the covariance matrix is nearly singular, is more concerning, but since these DSGE models typically aren't well identified and this is just meant as a simple example, I didn't worry about it.
